### ISSUE TITLE
Playbook fails on Ansible 2.9

### ISSUE THREAD

**Issue by dbeech** [cloudera/cloudera-playbook#56]
**Error message:**

```
TASK [scm : Extract the host identifiers and names into facts]
****************************************************
task path: /root/cloudera-playbook/roles/scm/tasks/main.yml:81
fatal: [...]: FAILED! => {
   “msg”: “An unhandled exception occurred while running the lookup plugin ‘template’. Error was a <type ‘exceptions.AttributeError’>, original message: ‘VariableManager’ object has no attribute ‘_loader’”
}
```

**Version details:**

```
ansible --version
ansible 2.9.0
 config file = /root/.ansible.cfg
 configured module search path = [u’/root/.ansible/plugins/modules’, u’/usr/share/ansible/plugins/modules’]
 ansible python module location = /usr/lib/python2.7/site-packages/ansible
 executable location = /usr/bin/ansible
 python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

Could be related to https://github.com/ansible/ansible/issues/57437 ?

**Comment by dbeech** [comment]
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 592, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 296, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 431, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 619, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 574, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 833, in do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 193, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 727, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/lookup/template.py", line 112, in run
    convert_data=convert_data_p, escape_backslashes=False)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 574, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 833, in do_template
    res = j2_concat(rf)
  File "<template>", line 13, in root
  File "/usr/lib64/python2.7/_abcoll.py", line 387, in iteritems
    yield (key, self[key])
  File "/usr/lib/python2.7/site-packages/ansible/vars/hostvars.py", line 83, in __getitem__
    data = self.raw_get(host_name)
  File "/usr/lib/python2.7/site-packages/ansible/vars/hostvars.py", line 80, in raw_get
    return self._variable_manager.get_vars(host=host, include_hostvars=False)
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 178, in get_vars
    _hosts_all=_hosts_all,
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 443, in _get_magic_variables
    variables['playbook_dir'] = os.path.abspath(self._loader.get_basedir())
AttributeError: 'VariableManager' object has no attribute '_loader'
```

**Comment by dbeech** [comment]
I raised a bug report with Ansible. https://github.com/ansible/ansible/issues/64745. 

For now we should avoid 2.9.0 until this bug is fixed in a maintenance release. I will add a note in the readme to that effect.

**Comment by dbeech** [comment]
Ansible 2.9.1 is released. Confirmed that the bug is fixed in this version -- closing.
